require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe WeightEntriesController do

  # This should return the minimal set of attributes required to create a valid
  # WeightEntry. As you add validations to WeightEntry, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all weight_entries as @weight_entries" do
      weight_entry = WeightEntry.create! valid_attributes
      get :index
      assigns(:weight_entries).should eq([weight_entry])
    end
  end

  describe "GET show" do
    it "assigns the requested weight_entry as @weight_entry" do
      weight_entry = WeightEntry.create! valid_attributes
      get :show, :id => weight_entry.id.to_s
      assigns(:weight_entry).should eq(weight_entry)
    end
  end

  describe "GET new" do
    it "assigns a new weight_entry as @weight_entry" do
      get :new
      assigns(:weight_entry).should be_a_new(WeightEntry)
    end
  end

  describe "GET edit" do
    it "assigns the requested weight_entry as @weight_entry" do
      weight_entry = WeightEntry.create! valid_attributes
      get :edit, :id => weight_entry.id.to_s
      assigns(:weight_entry).should eq(weight_entry)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new WeightEntry" do
        expect {
          post :create, :weight_entry => valid_attributes
        }.to change(WeightEntry, :count).by(1)
      end

      it "assigns a newly created weight_entry as @weight_entry" do
        post :create, :weight_entry => valid_attributes
        assigns(:weight_entry).should be_a(WeightEntry)
        assigns(:weight_entry).should be_persisted
      end

      it "redirects to the created weight_entry" do
        post :create, :weight_entry => valid_attributes
        response.should redirect_to(WeightEntry.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved weight_entry as @weight_entry" do
        # Trigger the behavior that occurs when invalid params are submitted
        WeightEntry.any_instance.stub(:save).and_return(false)
        post :create, :weight_entry => {}
        assigns(:weight_entry).should be_a_new(WeightEntry)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        WeightEntry.any_instance.stub(:save).and_return(false)
        post :create, :weight_entry => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested weight_entry" do
        weight_entry = WeightEntry.create! valid_attributes
        # Assuming there are no other weight_entries in the database, this
        # specifies that the WeightEntry created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        WeightEntry.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => weight_entry.id, :weight_entry => {'these' => 'params'}
      end

      it "assigns the requested weight_entry as @weight_entry" do
        weight_entry = WeightEntry.create! valid_attributes
        put :update, :id => weight_entry.id, :weight_entry => valid_attributes
        assigns(:weight_entry).should eq(weight_entry)
      end

      it "redirects to the weight_entry" do
        weight_entry = WeightEntry.create! valid_attributes
        put :update, :id => weight_entry.id, :weight_entry => valid_attributes
        response.should redirect_to(weight_entry)
      end
    end

    describe "with invalid params" do
      it "assigns the weight_entry as @weight_entry" do
        weight_entry = WeightEntry.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        WeightEntry.any_instance.stub(:save).and_return(false)
        put :update, :id => weight_entry.id.to_s, :weight_entry => {}
        assigns(:weight_entry).should eq(weight_entry)
      end

      it "re-renders the 'edit' template" do
        weight_entry = WeightEntry.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        WeightEntry.any_instance.stub(:save).and_return(false)
        put :update, :id => weight_entry.id.to_s, :weight_entry => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested weight_entry" do
      weight_entry = WeightEntry.create! valid_attributes
      expect {
        delete :destroy, :id => weight_entry.id.to_s
      }.to change(WeightEntry, :count).by(-1)
    end

    it "redirects to the weight_entries list" do
      weight_entry = WeightEntry.create! valid_attributes
      delete :destroy, :id => weight_entry.id.to_s
      response.should redirect_to(weight_entries_url)
    end
  end

end
